apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  replicas: 1 # Number of Pods
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: rahmamessadi23/devops:latest # Your DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8181 # Port your app exposes
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m" # Optional Java options
